### ISSUE TITLE
LibreOffice helpers still not working

### ISSUE THREAD

**Issue by amicalmant** [gkarsay/parlatype#60] opened 2018-11-29 17:22 UTC
### Installation and version

I installed Parlatype first from the Linux Mint repository and, later, from the Ubuntu PPA (https://launchpad.net/~gabor-karsay/+archive/ubuntu/parlatype), both version 1.5.6.

### My desktop environment

* Linux Mint 19 Tara
* Desktop: Cinnamon
* LibreOffice version: LibreOffice 6.1.3.2

### Issue

The keyboard controls from within Parlatype work fine but the LibreOffice PlayPause and JumpBack macros triggers this error every time I try to use them:

> A scripting structure error occurred while running scriptvnd.sun.star.script:Parlatype.py$PlayPause?language=Python&location=share in Python.
> 
> Message : <class 'ImportError'>: No module named 'dbus'
> File "/opt/libreoffice6.1/program/pythonscript.py", line 1047, in getScript
> mod = self.provCtx.getModuleByUrl( fileUri )
> File "/opt/libreoffice6.1/program/pythonscript.py", line 484, in getModuleByUrl
> exec(code, entry.module.dict)
> File "/opt/libreoffice6.1/share/Scripts/python/Parlatype.py", line 22, in
> import dbus
> File "/opt/libreoffice6.1/program/uno.py", line 347, in _uno_import
> return _builtin_import(name, *optargs, **kwargs)

#### Did it work in the past?
I don't know since I just installed the package yesterday with this configuration.

#### Other noticeable modules installed:
* gnome-settings-daemon (3.28.1-0ubuntu1.1) bionic
* dbus v1.12.2-1ubuntu1
* python-dbus v1.2.6-1

#### How to reproduce:
* Start Linux Mint 19
* Install LibreOffice 6.1.3.2 and Parlatype 1.5.6. from Ubuntu PPA
* Copy Parlatype.py either to /opt/libreoffice6.1/share/Scripts/python/ (as above) or to ~/.config/libreoffice/4/user/Scripts/python/ (it crashes too)
* Start LibreOffice
* Add Parlatype's PlayPause macro to F2 key in the Tools > Customize > Keyboard panel
* Open a Writer text file and an audio file in Parlatype
* Hit the F2 key

**Comment by gkarsay** [comment] 2019-02-07 16:20
First of all I'm sorry for the late answer. I saw it, but your setup is different to mine and I still don't have a clue. Anyway, thank you for the detailed description.

I have to guess: Maybe you need python3-dbus. Is it installed? If no, does `sudo apt-get install python3-dbus` change anything?

**Comment by amicalmant** [comment] 2019-02-07 16:45
> I have to guess: Maybe you need python3-dbus. Is it installed? If no, does `sudo apt-get install python3-dbus` change anything?

Yes it was installed (version 1.2.6-1). In the meantime, I have upgraded to LibreOffice 6.1.4.2, uninstalled and reinstalled Parlatype and its LO macro package. Still crashes and the error message is the same.

> Anyway, thank you for the detailed description.
You're welcome. If you cannot reproduce, let's just forget it. I will try again in a couple of years. :-)

**Comment by gkarsay** [comment] 2019-02-10 07:30
I could reproduce this on Ubuntu 18.04. Not with LibreOffice from the main archive nor from PPA (https://launchpad.net/~libreoffice/+archive/ubuntu/ppa) but with the deb packages offered by The Document Foundation at https://www.libreoffice.org/download/download/?type=deb-x86_64.

This seems to be the one you used because it's also installed in /opt. Or have you built it from source? The main archive and PPA seem to use the default system python interpreter while this one uses its own shipped python interpreter with a small set of modules. Obviously it doesn't have the dbus module needed. I don't know how to a) make it use the system python interpreter with all its modules or how to b) add a module to the shipped python interpreter.

I'm closing this because I can't support this kind of installation, only the default installation (no matter which distribution). Just for reference, the built-in python interpreter is at /opt/libreoffice6.2/program/python-core-3.5.5. I guess you would have to do something with lib/site.py in that folder to add a module.

**Closed by gkarsay** 2019-02-10 07:30 UTC

**Comment by amicalmant** [comment] 2019-04-10 00:27
Sorry, I did not see this earlier. I really appreciate the efforts you made in order to investigate this.

You are right: I don't use the PPA version of LO which is always outdated but the  fresh deb version offered by the Foundation.

I am a little deceived that this config is not supported but I don't blame you at all. Thanks for your open source commitment and much appreciated follow up.
