### ISSUE TITLE
Xfce: media keys work in media players (Rhythmbox, Quod Libet, etc.) but not in Parlatype

### ISSUE THREAD

**Issue by space-trash** [gkarsay/parlatype#58] opened 2018-11-07 21:43 UTC
### Installation and version

How did you install Parlatype? Tarball. Version: Parlatype 1.5.4.

### Your desktop environment

* What's your distro? Mint 18.3
* What's your desktop environment? XFCE. Media keys work perfectly across the board in Cinnamon, by the way (Rhythmbox, Quod Libet, Parlatype...). I'd rather use XFCE if I could, though. 

### Issue

* What is not working as expected? My media keys work in Rhythmbox, Quod Libet and any media player I'm using, but not in Parlatype. 
* Does it happen all the time? Yes. Every time.
* Did it work in the past (a regression)? No, it never worked. I tried Parlatype (1.5.4) in XFCE (I think I was on Mint 18.1 or 18.2 then) about a year ago or so, and wasn't able to get it to work. 
* What steps are needed to reproduce it? Install Parlatype in XFCE, launch it, load a file, use your media keys, watch them not do anything.
* If you start Parlatype from terminal, is there any error output? No.

**Comment by space-trash** [comment] 2018-11-07 22:05
By the way, I just tried MATE as well. Same behavior as XFCE.

**Comment by space-trash** [comment] 2018-11-07 22:31
Also: I noticed Parlatype 1.5.6 had come out this summer. Same problem happens in XFCE with 1.5.6. 

Everything's fine in Cinnamon/1.5.6.

Haven't had time to try MATE with 1.5.6 yet.

**Comment by gkarsay** [comment] 2018-12-02 19:56
Thanks for your report and sorry for the late reply! My first guess is that XFCE doesn't use GNOME Media Keys at all but uses the MPRIS Interface instead. Many media players have a plugin system where you can turn plugins on or off. If you turn the MPRIS plugin in Quodlibet off, does it still work then?

**Comment by space-trash** [comment] 2018-12-13 23:35
Thanks for the reply (my own is late too; haven't checked github in a while).

I no longer have other desktops installed and I'm quite busy at the moment (finals!), so I'll have to wait to do some more testing. Just an update, though, in case you want to try some things on your own:

My previous install of Mint 18.3 Cinnamon version had gotten quite buggy (random hang ups which I didn't have on Windows (same computer, dual boot)). Since Mint 19 and LMDE 3 had come out I figured I'd give both a shot, and in both cases, I had the same problem: media keys didn't work in Parlatype while they worked in other programs.

Now, this is where it gets funny: as I rely a lot on Parlatype, I went back to a fresh install of Mint 18.3, Cinnamon version, and the first program I installed was Parlatype 1.5.6 from the main repository, and... media keys didn't work. Tried Parlatype 1.5.4, didn't work either, out of the box.  

So, contrarily to what I mentioned in my first post, media keys do _not_ work out of the box in Cinnamon. What stands true, though, is that on that Mint 18.3 install with multiple desktop environments, media keys would work in Parlatype in Cinnamon, but not in other DEs I mentioned.

Right now, I am using Parlatype 1.5.4. on Mint 18.3 (Cinnamon version), and media keys _work_ in Parlatype, even though they didn't work out of the box (they worked out of the box with other media players). But truth be told, I forget exactly what I did to get the keys to work. I'm pretty sure installing from tarball or flatpak  didn't work out of the box.

Maybe it doesn't make any sense (I'm a complete noob), but I went and installed all of the dependencies mentioned here: https://github.com/gkarsay/parlatype (after I had already installed parlatype 1.5.4).

Did I reinstall parlatype after that? I'm not sure. I don't remember.

It's been a while, but I'm pretty sure media keys worked properly after that. I remember at least some of the dependencies needed to be installed or updated, during the process. Did any of them have anything to do with media keys? You would know better than I would, that's for sure.

**Comment by gkarsay** [comment] 2021-11-27 19:06
I'm closing this now as it's not really actionable and my suspicion is that it's a duplicate of #86. Parlatype currently supports GNOME MediaKeys, which is one of many ways to control media players. However, this is very GNOME specific and doesn't work on many other DEs (although I don't know which ones exactly). I you have several DEs installed, chances are higher that it works.

MPRIS on the other hand is supported by most DEs and many applications (including Rhythmbox and Quod Libet), that's why I take it as a duplicate of #86.

**Closed by gkarsay** 2021-11-27 19:06 UTC
