### ISSUE TITLE
Is it possible to use Parlatype with Mozilla's open source speech project?

### ISSUE THREAD

**Issue by LinuxBeaver** [gkarsay/parlatype#83] opened 2021-04-21 03:53 UTC
Hey, nice software you have. I am just asking if it is possible to configure Parlatype to use Mozilla's open speech project as opposed to just CMUSphinx?

**Comment by gkarsay** [comment] 2021-04-25 20:47
Currently it's not possible to use Mozilla Deepspeech. I'm working on it since quite a while but it's not ready yet.

**Comment by gkarsay** [comment] 2021-05-23 12:09
Closing as a duplicate of #71

**Closed by gkarsay** 2021-05-23 12:09 UTC
