### ISSUE TITLE
Please Update Parlatype Runtime from Gnome 40 and branch 20.08

### ISSUE THREAD

**Issue by reallyrez** [gkarsay/parlatype#106] opened 2023-02-07 01:56 UTC
When I installed/updated flatpak, I got this message:

Info: runtime org.gnome.Platform branch 40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   org.parlatype.Parlatype

Info: runtime org.freedesktop.Platform.VAAPI.Intel branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.parlatype.Parlatype

Info: runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.parlatype.Parlatype

I have Parlatype 3.1

Thanks!

**Comment by gkarsay** [comment] 2023-02-18 14:46
Done, that's a duplicate of #102

**Closed by gkarsay** 2023-02-18 14:46 UTC
